Description: |
  Deploys an ApplicationLoadBalancer
Parameters:
  ALBPort:
    Type: String
    Default: 80
  ContainerPort:
    Description: Port of Web api on docker
    Type: String
    Default: 5000
Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${AWS::StackName}-ALB"
      SecurityGroups:
        - Fn::ImportValue:
            "demo-sg-alb"
      Subnets:
        - Fn::ImportValue:
            "demo-PublicSubnet1"
        - Fn::ImportValue:
            "demo-PublicSubnet2"
  ApplicationLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref 'TargetGroup'
      LoadBalancerArn: !Ref 'ApplicationLoadBalancer'
      Port: !Ref ALBPort
      Protocol: HTTP
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn:
      - ApplicationLoadBalancer
    Properties:
      Name: !Sub "${AWS::StackName}-tg"
      Port: !Ref ContainerPort
      TargetType: instance
      Protocol: HTTP
      VpcId:
        Fn::ImportValue:
            "demo-VPC"

      HealthCheckTimeoutSeconds: 15
      HealthCheckIntervalSeconds: 20
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: 200
Outputs:
  Listener:
    Description: ApplicationLoadBalancer Listener
    Value: !Ref 'ApplicationLoadBalancerListener'
  ApplicationLoadBalancerEndpoint:
    Description: DNS name of the ApplicationLoadBalancer
    Value: !GetAtt 'ApplicationLoadBalancer.DNSName'
  TargetGroup:
    Description: TargetGroup for ABL
    Value: !Ref TargetGroup
    Export:
        Name: "demo-targetgroup"
